---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: "12.4.0"

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.7
  - name: centos-5.11

suites:
  - name: el5
    run_list:
      - recipe[chef-updater::default]
    attributes:
      chef-updater:
        package_source: "https://opscode-omnibus-packages.s3.amazonaws.com/el/5/x86_64/chef-12.5.1-1.el5.x86_64.rpm"
        package_version: "12.5.1-1"
    includes:
      - centos-5.11
  - name: el6
    run_list:
      - recipe[chef-updater::default]
    attributes:
      chef-updater:
        package_source: "https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-12.5.1-1.el6.x86_64.rpm"
        package_version: "12.5.1-1"
    includes:
      - centos-6.7
  - name: el7
    run_list:
      - recipe[chef-updater::default]
    attributes:
      chef-updater:
        package_source: "https://opscode-omnibus-packages.s3.amazonaws.com/el/7/x86_64/chef-12.5.1-1.el7.x86_64.rpm"
        package_version: "12.5.1-1"
    includes:
      - centos-7.1
  - name: ubuntu
    run_list:
      - recipe[chef-updater::default]
    attributes:
      chef-updater:
        package_source: "https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.5.1-1_amd64.deb"
        package_version: "12.5.1-1"
    includes:
      - ubuntu-12.04
      - ubuntu-14.04
